[package]
name = "sym-engine"
version = "0.1.0"
authors = ["Robert Sedlacek <rs@474.at>"]
edition = "2018"

[dependencies]
fnv = "1.0.7"
string_cache = "0.8.1"
nom = "6.1.2"
nom-greedyerror = "0.3.1"
nom_locate = "3.0.1"
float-ord = "0.3.1"
num-traits = "0.2.14"
